const movies = [
    "gladiator",
    "the dark knight",
    "slumdog millionaire",
    "the departed",
    "pan's labyrinth",
    "blood diamond",
    "city of god",
    "finding nemo",
    "no country for old men",
    "cinderella man",
    "v for vendetta",
    "there will be blood",
    "donnie darko",
    "sin city",
    "mystic river",
    "300",
    "let the right one in",
    "a beautiful mind",
    "munich",
    "up",
    "memento",
    "the prestige",
    "wall-e",
    "requiem for a dream",
    "into the wild",
    "the pianist",
    "inglorious basterds",
    "the lord of the rings trilogy",
    "lost in translation",
    "the hurt locker",
    "eternal sunshine of the spotless mind",
    "crouching tiger, hidden dragon",
    "american psycho",
    "kill bill: vol 1",
    "road to perdition",
    "walk the line",
    "the last samurai",
    "million dollar baby",
    "o brother, where art thou",
    "downfall",
    "black hawk down",
    "hotel rwanda",
    "the curious case of benjamin button",
    "eastern promises",
    "little miss sunshine",
    "the incredibles",
    "american gangster",
    "gran torino"
]
function newMovie(){
let randomNumber = Math.floor(Math.random() * (movies.length));
document.getElementById('movieDisplay').innerHTML = movies[randomNumber];
}
